### ISSUE TITLE
TODO: Quasar 0.14

### ISSUE THREAD

**Issue by leopiccionia** [leopiccionia/quasar-helper-json#1]
- [ ] Layout
- [ ] Navigation
	- [X] Toolbar
	- [ ] Tabs
	- [ ] Pull to refresh
	- [ ] Layout side links
	- [ ] Handling back button
	- [ ] Context menu
	- [ ] Breadcrumb
	- [ ] Pagination
- [ ] Scrolling
	- [ ] Scroll observable
	- [ ] Scroll directive
	- [ ] Infinite scroll
	- [ ] Scroll area
	- [ ] Scroll fire
	- [ ] Back to top
	- [ ] Scrolling utils
- [ ] Forms
	- [ ] Button
	- [ ] Field
	- [ ] Input
	- [ ] Form validation
	- [ ] Chips input
	- [ ] Autocomplete
	- [ ] Search
	- [ ] Slider
	- [ ] Range
	- [ ] Radio
	- [ ] Checkbox
	- [ ] Toggle
	- [ ] Option group
	- [ ] Datetime
	- [ ] Inline datetime
	- [ ] Datetime range
	- [ ] Select
	- [ ] Dialog select
	- [ ] Rating
	- [ ] Knob
	- [ ] Uploader
- [ ] Popups
	- [ ] Action sheet
	- [ ] Alert
	- [ ] Toast
	- [ ] Dialog
	- [ ] Modal
	- [X] Popover
	- [X] Tooltip
- [ ] Grouping
	- [ ] Card
	- [ ] Collapsible
	- [ ] DataTable
	- [ ] HTML Table
	- [ ] List and list items
	- [ ] Carousel
	- [ ] Stepper
- [ ] Progress
	- [ ] Ajax Bar
	- [ ] Loading
	- [ ] Inner loading
	- [ ] Progress bar
	- [ ] Spinner
- [ ] Touch/mouse actions
	- [ ] Panning
	- [ ] Swiping
	- [ ] Touch hold
- [X] Media
	- [X] Image gallery
	- [X] Parallax
	- [X] Video embedding
- [ ] Animation
	- [ ] Transition
	- [ ] Slide transition
	- [ ] JS animations
	- [ ] Animation CSS helper classes
- [ ] Other components
	- [ ] Chip
	- [ ] Chat
	- [ ] Tree
